### ISSUE TITLE
csv files recipe/machines

### ISSUE THREAD

**Issue by DirectionAndMagnitude** [svikramank/DeepRLForFactoryOptimization#1]
Hello,

Thanks for this interesting project.  Can you provide these missing CSV files?

recipes = pd.read_csv('~/Desktop/GSR/fall19/random/test/recipes.csv')
machines = pd.read_csv('~/Desktop/GSR/fall19/random/test/machines.csv')

**Comment by osseney** [comment]
I am wondering if you received that CSV.

**Comment by POJIANWU** [comment]
> 我想知道您是否收到了该 CSV。

Hello,I'm interested in your project,can you provide these CSV files for me?
